jobs:
  build:
    env:
      EXTRA_BUCK_ARGS: -v 0
      EXTRA_OKBUCK_ARGS: --quiet --stacktrace
      SKIP_OKBUCK: true
    name: Okbuck CI Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Run ${{ matrix.build_cmd }}
      run: ./tooling/ci/build_cmd.sh ${{ matrix.build_cmd }}
    - continue-on-error: true
      if: success() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      name: Upload snapshot
      run: ./gradlew publish -PmavenCentralUsername="${{ secrets.SonatypeUsername
        }}" -PmavenCentralPassword="${{ secrets.SonatypePassword }}"
    strategy:
      matrix:
        build_cmd:
        - build
        - lint
        - test
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
